### ISSUE TITLE
How do I add a new version

### ISSUE THREAD

**Issue by shawnholt** [progressivetech/civi-schema-harmonizer#1]
How do I get a "Clean" schema definition (for drush method)? Do I need a fresh install to create this?
I followed instructions with mysql which creates:
4.6.2.create.tables.reference.txt
4.6.2.tables.reference.txt

but how is the json file generated?  I still get error: I can't find a schema file for your database version

**Comment by stevekessler** [comment]
@shawnholt  I am wondering the same thing.

**Comment by stevekessler** [comment]
I got this to work just by copying the older .json file.  I am not 100% sure this was the best idea but it worked and FIXED my install.

**Comment by shawnholt** [comment]
@steveKessler could you be a bit more specific about which versions and files?

**Comment by stevekessler** [comment]
I copied the 4.5.8.fks.json file and named it with the new version of CiviCRM this worked like a charm. 

I am just not sure what should or should not be in that file.

**Comment by jmcclelland** [comment]
Hi - The foreign key settings don't change much between minor versions so what you did is probably fine. However, the best way to do it is the install a fresh copy of CivICRM that is the same version as your database and then run:

drush cfk-generate

That will generate a schema file for your version.

I just updated the documentation (and fixed a bug) so this is possible.
