### ISSUE TITLE
No Module File

### ISSUE THREAD

**Issue by stevekessler** [progressivetech/civi-schema-harmonizer#2]
Drush would not run without a module file. So what I did was renamed the .php file to .module and changed the required function to point to the .module file.  

I also had to create a .info file.

**Comment by jmcclelland** [comment]
Hi,

Did you install civi-schema-harmonizer in the .drush directory of your home directory? I think it should work fine if it's in your ~/.drush directory, even if there is no .module file. However, the .module file may be necessary if you put this in your sites/all/modules directory, for example.

Also - what version of drush are you using? Maybe I'm using an older version and something has changed.

**Comment by stevekessler** [comment]
I am using Drush 6.2.0.  I was not sure where to put it so I put in the /sites/all/modules folder.  This is probably why I needed to convert it to a module.  A not on where to put it  in the help text would be great :) 

I appreciate your hard work and publishing this script.

**Comment by jmcclelland** [comment]
Agreed about needing clearer directions. I've added it to the README file (1736fbcf4d5ab544e99aa30fdda56bed78df916a). Thanks for the testing - it really makes a big difference.
